package com.wang.masssms.model.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACTS".
 */
public class Contacts {

    private Long id;
    private Integer phonenumber;
    private Integer name;
    private Integer groupid;
    private java.util.Date creattime;
    private java.util.Date lastmodify;

    public Contacts() {
    }

    public Contacts(Long id) {
        this.id = id;
    }

    public Contacts(Long id, Integer phonenumber, Integer name, Integer groupid, java.util.Date creattime, java.util.Date lastmodify) {
        this.id = id;
        this.phonenumber = phonenumber;
        this.name = name;
        this.groupid = groupid;
        this.creattime = creattime;
        this.lastmodify = lastmodify;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPhonenumber() {
        return phonenumber;
    }

    public void setPhonenumber(Integer phonenumber) {
        this.phonenumber = phonenumber;
    }

    public Integer getName() {
        return name;
    }

    public void setName(Integer name) {
        this.name = name;
    }

    public Integer getGroupid() {
        return groupid;
    }

    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    public java.util.Date getCreattime() {
        return creattime;
    }

    public void setCreattime(java.util.Date creattime) {
        this.creattime = creattime;
    }

    public java.util.Date getLastmodify() {
        return lastmodify;
    }

    public void setLastmodify(java.util.Date lastmodify) {
        this.lastmodify = lastmodify;
    }

}
