package com.wang.masssms.model.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACT_TO_GROUP".
 */
public class ContactToGroup {

    private Long id;
    private Integer cid;
    private Integer gid;

    public ContactToGroup() {
    }

    public ContactToGroup(Long id) {
        this.id = id;
    }

    public ContactToGroup(Long id, Integer cid, Integer gid) {
        this.id = id;
        this.cid = cid;
        this.gid = gid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCid() {
        return cid;
    }

    public void setCid(Integer cid) {
        this.cid = cid;
    }

    public Integer getGid() {
        return gid;
    }

    public void setGid(Integer gid) {
        this.gid = gid;
    }

}
