package com.wang.masssms.model.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACT_GROUP".
 */
public class ContactGroup {

    private Long id;
    private String name;
    private java.util.Date creatTime;

    public ContactGroup() {
    }

    public ContactGroup(Long id) {
        this.id = id;
    }

    public ContactGroup(Long id, String name, java.util.Date creatTime) {
        this.id = id;
        this.name = name;
        this.creatTime = creatTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getCreatTime() {
        return creatTime;
    }

    public void setCreatTime(java.util.Date creatTime) {
        this.creatTime = creatTime;
    }

}
