package com.wang.masssms.model.orm;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.wang.masssms.model.orm.GroupToMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GROUP_TO_MESSAGE".
*/
public class GroupToMessageDao extends AbstractDao<GroupToMessage, Long> {

    public static final String TABLENAME = "GROUP_TO_MESSAGE";

    /**
     * Properties of entity GroupToMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Gid = new Property(1, Long.class, "gid", false, "GID");
        public final static Property Mid = new Property(2, Long.class, "mid", false, "MID");
    };

    private DaoSession daoSession;

    private Query<GroupToMessage> contactGroup_GroupToMessageListQuery;
    private Query<GroupToMessage> message_GroupToMessageListQuery;

    public GroupToMessageDao(DaoConfig config) {
        super(config);
    }
    
    public GroupToMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GROUP_TO_MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"GID\" INTEGER," + // 1: gid
                "\"MID\" INTEGER);"); // 2: mid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GROUP_TO_MESSAGE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GroupToMessage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long gid = entity.getGid();
        if (gid != null) {
            stmt.bindLong(2, gid);
        }
 
        Long mid = entity.getMid();
        if (mid != null) {
            stmt.bindLong(3, mid);
        }
    }

    @Override
    protected void attachEntity(GroupToMessage entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GroupToMessage readEntity(Cursor cursor, int offset) {
        GroupToMessage entity = new GroupToMessage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // gid
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // mid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GroupToMessage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGid(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setMid(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GroupToMessage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GroupToMessage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "groupToMessageList" to-many relationship of ContactGroup. */
    public List<GroupToMessage> _queryContactGroup_GroupToMessageList(Long gid) {
        synchronized (this) {
            if (contactGroup_GroupToMessageListQuery == null) {
                QueryBuilder<GroupToMessage> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Gid.eq(null));
                contactGroup_GroupToMessageListQuery = queryBuilder.build();
            }
        }
        Query<GroupToMessage> query = contactGroup_GroupToMessageListQuery.forCurrentThread();
        query.setParameter(0, gid);
        return query.list();
    }

    /** Internal query to resolve the "groupToMessageList" to-many relationship of Message. */
    public List<GroupToMessage> _queryMessage_GroupToMessageList(Long mid) {
        synchronized (this) {
            if (message_GroupToMessageListQuery == null) {
                QueryBuilder<GroupToMessage> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Mid.eq(null));
                message_GroupToMessageListQuery = queryBuilder.build();
            }
        }
        Query<GroupToMessage> query = message_GroupToMessageListQuery.forCurrentThread();
        query.setParameter(0, mid);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getContactGroupDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getMessageDao().getAllColumns());
            builder.append(" FROM GROUP_TO_MESSAGE T");
            builder.append(" LEFT JOIN CONTACT_GROUP T0 ON T.\"GID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN MESSAGE T1 ON T.\"MID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected GroupToMessage loadCurrentDeep(Cursor cursor, boolean lock) {
        GroupToMessage entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ContactGroup contactGroup = loadCurrentOther(daoSession.getContactGroupDao(), cursor, offset);
        entity.setContactGroup(contactGroup);
        offset += daoSession.getContactGroupDao().getAllColumns().length;

        Message message = loadCurrentOther(daoSession.getMessageDao(), cursor, offset);
        entity.setMessage(message);

        return entity;    
    }

    public GroupToMessage loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<GroupToMessage> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<GroupToMessage> list = new ArrayList<GroupToMessage>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<GroupToMessage> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<GroupToMessage> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
