package com.wang.masssms.model.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE".
 */
public class Message {

    private Long id;
    private java.util.Date sendtime;
    private Integer gid;
    private String text;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, java.util.Date sendtime, Integer gid, String text) {
        this.id = id;
        this.sendtime = sendtime;
        this.gid = gid;
        this.text = text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getSendtime() {
        return sendtime;
    }

    public void setSendtime(java.util.Date sendtime) {
        this.sendtime = sendtime;
    }

    public Integer getGid() {
        return gid;
    }

    public void setGid(Integer gid) {
        this.gid = gid;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

}
