package com.wang.masssms.model.orm;

import java.util.List;
import com.wang.masssms.model.orm.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE".
 */
public class Message {

    private Long id;
    private java.util.Date sendtime;
    private String text;
    private Boolean iscollect;
    private Boolean isdraft;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MessageDao myDao;

    private List<ContactToMessage> mid;
    private List<GroupToMessage> groupToMessageList;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, java.util.Date sendtime, String text, Boolean iscollect, Boolean isdraft) {
        this.id = id;
        this.sendtime = sendtime;
        this.text = text;
        this.iscollect = iscollect;
        this.isdraft = isdraft;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMessageDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getSendtime() {
        return sendtime;
    }

    public void setSendtime(java.util.Date sendtime) {
        this.sendtime = sendtime;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Boolean getIscollect() {
        return iscollect;
    }

    public void setIscollect(Boolean iscollect) {
        this.iscollect = iscollect;
    }

    public Boolean getIsdraft() {
        return isdraft;
    }

    public void setIsdraft(Boolean isdraft) {
        this.isdraft = isdraft;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ContactToMessage> getMid() {
        if (mid == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ContactToMessageDao targetDao = daoSession.getContactToMessageDao();
            List<ContactToMessage> midNew = targetDao._queryMessage_Mid(id);
            synchronized (this) {
                if(mid == null) {
                    mid = midNew;
                }
            }
        }
        return mid;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetMid() {
        mid = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<GroupToMessage> getGroupToMessageList() {
        if (groupToMessageList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            GroupToMessageDao targetDao = daoSession.getGroupToMessageDao();
            List<GroupToMessage> groupToMessageListNew = targetDao._queryMessage_GroupToMessageList(id);
            synchronized (this) {
                if(groupToMessageList == null) {
                    groupToMessageList = groupToMessageListNew;
                }
            }
        }
        return groupToMessageList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetGroupToMessageList() {
        groupToMessageList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
